### PR TITLE
Drain master end of pty to prevent stderr from hanging

### LINKED ISSUE #347: Container's stderr is not populated in logs
What are the steps to reproduce this issue?
-------------------------------------------
1. Launch pod without allocated tty
2. Start following logs

```
apiVersion: v1
kind: Pod
metadata:
  name: int
spec:
  containers:
    - name: int
      image: cloud.sylabs.io/sashayakovtseva/test/test-info:interactive
      args: ["--interval", "1s"]
```

What happens?
-------------
After some period of time stderr entries no longer appear.

What were you expecting to happen?
----------------------------------
Stderr entries appear as usual.

Environment?
----------------------------------------
**OS distribution and version:** Linux node-1 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**go version:** go version go1.12.6 linux/amd64

**Singularity-CRI version:** v1.0.0-beta.4

**Singularity version:** 3.3.0-rc.1.461.g4a5397cdb

**Kubernetes version:** 1.15.1

### PR DESCRIPTION
**Pull request by sashayakovtseva**
Turned out if master end of pty is not drained, after some period of time no new stderr entries appear in container's logs. This may happen due to buffer overflow, and this PR fixes it by simply draining master end.

Fixes #347

### CODE REVIEW

File: pkg/singularity/runtime/client_oci.go [hunk 1]
```diff
@@ -122,6 +123,7 @@ func (c *CLIClient) Create(id, bundle string, stdin, tty bool, flags ...string)
 			glog.V(5).Info("Starting stream copying from master to stderr")
 			_, err := io.Copy(os.Stderr, syio.NewContextReader(ctx, master))
 			glog.V(5).Infof("Stream copying returned: %v", err)
+			go io.Copy(ioutil.Discard, master)
```
Comment (cali4888) [inline pkg/singularity/runtime/client_oci.go]: Leave a comment please
